apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base
replicas:
- count: 5
  name: deployment
images:
- name: 335270644332.dkr.ecr.ap-northeast-1.amazonaws.com/staging-sample-app
  newName: 335270644332.dkr.ecr.ap-northeast-1.amazonaws.com/production-sample-app
